# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.Dockerfile
        image: amirmarmul:nginx
        ports:
            - '${APP_PORT:-80}:80'
        depends_on:
            - laravel
    laravel:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        image: amirmarmul:php
        environment:
            APP_NAME:
            APP_ENV:
            APP_KEY:
            APP_DEBUG:
            APP_URL:
            LOG_CHANNEL:
            DB_CONNECTION:
            DB_HOST:
            DB_DATABASE:
            DB_USERNAME:
            DB_PASSWORD:
            MAIL_MAILER:
            MAIL_HOST:
            MAIL_PORT:
            MAIL_USERNAME:
            MAIL_PASSWORD:
            MAIL_ENCRYPTION:
            MAIL_FROM_ADDRESS:
            MAIL_FROM_NAME:
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql:8.0'
        environment:
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql_data:/var/lib/mysql'
    redis:
        image: 'redis:alpine'
        volumes:
            - 'redis_data:/data'
networks:
    sail:
        driver: bridge
volumes:
    mysql_data:
        driver: local
    redis_data:
        driver: local
